### ISSUE TITLE
Fails to build against libxml 2.14

### ISSUE THREAD

**Issue by sthibaul** [liblouis/liblouisxml#6]
Hello,

As noticed in debian, liblouisxml does not build with libxml 2.14: 
http://qa-logs.debian.net/2025/05/23/liblouisxml_2.4.0-14_unstable_libxml2.log

Samuel

**Comment by nwellnhof** [comment]
This was fixed in libxml2 2.14.2.

**Comment by sthibaul** [comment]
The build log is using libxml2 2.14.3

**Comment by nwellnhof** [comment]
Okay, the fix in 2.14.2 was incomplete.

**Comment by nwellnhof** [comment]
This will be fixed in libxml2 2.14.4. As a work-around, you can use `xmlSetGenericErrorFunc` instead of `initGenericErrorDefaultFunc`.

**Comment by sthibaul** [comment]
https://buildd.debian.org/status/fetch.php?pkg=liblouisxml&arch=ppc64el&ver=2.4.0-14%2Bb2&stamp=1755173203&raw=0

still failed with libxml2 2.14.5

**Comment by sthibaul** [comment]
Ah, but it's about ATTRIBUTE_UNUSED, which is unrelated to libxml2:

```
liblouisxml.c:49:30: error: expected ';', ',' or ')' before 'ATTRIBUTE_UNUSED'
   49 | liblouisxmlErrors (void *ctx ATTRIBUTE_UNUSED, const char *msg, ...)
```

**Comment by sthibaul** [comment]
@nwellnhof  Mmm, no, `initGenericErrorDefaultFunc` is still buggy:

https://salsa.debian.org/a11y-team/liblouisutdml/-/jobs/8027904

indeed, `(h) ? *(h) : NULL` makes no sense when `h` is NULL.

**Comment by sthibaul** [comment]
I.e. just make it `xmlSetGenericErrorFunc(NULL, h)`

**Comment by sthibaul** [comment]
Ah, no, they are not the same typing...

**Comment by sthibaul** [comment]
Submitted to https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/336
